version: '3.1'

services:
  application-service:
    platform: linux/amd64
    build: ./book-store-app
    ports:
      - "8080:8080"
        
  client-service:
    platform: linux/amd64
    build: ./client-app
    ports:
      - "8082:8082"

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
        
        
        
